# Generated by Django 3.1.5 on 2021-01-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=512)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('coordination', models.CharField(max_length=256)),
                ('phone', models.TextField()),
                ('mails', models.TextField()),
                ('websites', models.TextField()),
                ('datafile', models.FileField(upload_to='')),
                ('obtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objecttype')),
            ],
        ),
    ]
