# Generated by Django 3.1.5 on 2021-01-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='datafile',
            new_name='resultfile',
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='object',
            name='info_sys',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='ips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='subdomains',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='object',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='mails',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='websites',
            field=models.BooleanField(default=False),
        ),
    ]
