# Generated by Django 3.1.5 on 2021-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210119_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='info_sys',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='ips',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='mails',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='subdomains',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='websites',
            field=models.TextField(blank=True),
        ),
    ]
