# Generated by Django 3.1.5 on 2021-01-19 05:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_object_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2048)),
                ('verified', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('resultfile', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
