# Generated by Django 3.1.5 on 2021-01-19 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210119_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='websites',
        ),
        migrations.AddField(
            model_name='websites',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.object'),
            preserve_default=False,
        ),
    ]
