# Generated by Django 3.1.5 on 2021-01-21 11:27

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210121_0743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Давлат', 'verbose_name_plural': 'Давлатлар'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объектлар'},
        ),
        migrations.AlterModelOptions(
            name='objecttype',
            options={'verbose_name': 'Объект тури', 'verbose_name_plural': 'Объект турлари'},
        ),
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'verbose_name': 'Ресурс тури', 'verbose_name_plural': 'Ресурс турлари'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Ресултат', 'verbose_name_plural': 'Ресултатлар'},
        ),
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Сайт', 'verbose_name_plural': 'Сайтлар'},
        ),
        migrations.AddField(
            model_name='website',
            name='dirs',
            field=models.TextField(blank=True, verbose_name='Директориялар'),
        ),
        migrations.AddField(
            model_name='website',
            name='ip',
            field=models.CharField(blank=True, max_length=16, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='website',
            name='open_ports',
            field=models.TextField(blank=True, verbose_name='Очиқ портлар'),
        ),
        migrations.AddField(
            model_name='website',
            name='rtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.resourcetype', verbose_name='Ресурс тури'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='server_cor',
            field=models.CharField(blank=True, max_length=128, verbose_name='Сервер координатаси'),
        ),
        migrations.AddField(
            model_name='website',
            name='subdomains',
            field=models.TextField(blank=True, verbose_name='Суб доменлар'),
        ),
        migrations.AddField(
            model_name='website',
            name='tech',
            field=models.TextField(blank=True, verbose_name='Технология'),
        ),
        migrations.AddField(
            model_name='website',
            name='vulnerabilities',
            field=models.TextField(blank=True, verbose_name='Заифликлари'),
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.TextField(blank=True, verbose_name='Манзил'),
        ),
        migrations.AlterField(
            model_name='object',
            name='code',
            field=models.CharField(blank=True, max_length=512, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='object',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='object',
            name='coordination',
            field=models.CharField(blank=True, max_length=256, verbose_name='Кордината'),
        ),
        migrations.AlterField(
            model_name='object',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country', verbose_name='Давлат'),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(blank=True, verbose_name='Тавсиф'),
        ),
        migrations.AlterField(
            model_name='object',
            name='info_sys',
            field=models.TextField(blank=True, verbose_name='Ахборот тизимлари'),
        ),
        migrations.AlterField(
            model_name='object',
            name='ips',
            field=models.TextField(blank=True, verbose_name='IP адреслар'),
        ),
        migrations.AlterField(
            model_name='object',
            name='mails',
            field=models.TextField(blank=True, verbose_name='почталар'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.TextField(blank=True, verbose_name='Объект номи'),
        ),
        migrations.AlterField(
            model_name='object',
            name='obtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.objecttype', verbose_name='Объект тури'),
        ),
        migrations.AlterField(
            model_name='object',
            name='phone',
            field=models.TextField(blank=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='object',
            name='resultfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='Ресултат файл'),
        ),
        migrations.AlterField(
            model_name='object',
            name='subdomains',
            field=models.TextField(blank=True, verbose_name='Суб-доменлари'),
        ),
        migrations.AlterField(
            model_name='object',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Текширилган'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='result',
            name='resultfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='Ресултат файл'),
        ),
        migrations.AlterField(
            model_name='result',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.website', verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='website',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Текширилган'),
        ),
    ]
