# Generated by Django 3.1.5 on 2021-01-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210121_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурслар'},
        ),
        migrations.AddField(
            model_name='result',
            name='positive',
            field=models.BooleanField(default=False, verbose_name='Natija'),
        ),
    ]
