# Generated by Django 3.1.5 on 2021-01-25 14:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210125_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Ресултат'),
        ),
    ]
