# Generated by Django 3.1.5 on 2021-01-26 04:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210125_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Ресултат'),
        ),
    ]
