# Generated by Django 3.1.5 on 2021-01-26 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210126_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Ресултат'),
        ),
    ]
