# Generated by Django 3.1.5 on 2021-01-26 05:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210126_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ресултат'),
        ),
        migrations.AlterField(
            model_name='result',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Ресултат'),
        ),
    ]
