# Generated by Django 3.1.5 on 2021-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210126_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(max_length=2048, unique=True),
        ),
    ]
